import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* 
        Force the root body to be unscrollable, black-backed, 
        and take up exactly 100% of the hardware window bounds.
      */}
      <body className="m-0 p-0 bg-black overflow-hidden w-screen h-screen select-none">
        {children}
      </body>
    </html>
  );
}
